services:
  backend:
    build:
      context: ./backend
    container_name: task_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: task_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    command: npm run dev -- --host